### ISSUE TITLE
Requesting official CrossRef dumps

### ISSUE THREAD

**Issue by blahah** [elifesciences/datacapsule-crossref#22]
There are incredibly many uses for full dumps of the Crossref metadata, so I'm grateful for this project, and for it archiving its archives (and I will archive my own if I think they become sufficiently more recent).

Has anyone at eLife discussed with Crossref the potential benefits of them providing their own archives?

If not, I will initiate this conversation, but I imagine eLife might be better positioned to do so succesfully.

**Comment by de-code** [comment]
Apologies, I didn't notice your issue. I am closing this issue as Crossref are now providing official dumps.
(There had been discussions with Crossref before, including as part of the Open Citations workshop)

**Comment by ynnig** [comment]
Hi - yes the Crossref public data dump from March 2020 can be retrieved from [Academic Torrents](https://academictorrents.com/details/0c6c3fbfdc13f0169b561d29354ea8b188eb9d63). And FYI there will be a new one this month that will include the now-open Elsevier references (plus lots more abstracts and other additions from many other members).

**Comment by blahah** [comment]
@de-code and @ynnig thank you for responding - I'm very happy that this data is now available and discoverable.
